<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/01_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy is designed for numerical operations on entire arrays.**<br>
*So every operation are done on arrays only*

In [18]:
import numpy as np #Importing Library

In [19]:
numbers=np.array([10,20,30,40,50])  #Defining Arrays List 1D
print(numbers) #Printing Numbers

[10 20 30 40 50]


In [20]:
Numbers2D=np.array([[10,20,30],[40,50,60]]) #2D Array List Brackets Uses
print(Numbers2D) #Printing Numbers 2D

[[10 20 30]
 [40 50 60]]


In [22]:
Numbers3D=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[110,120,130]]]) #3D Array List Brackets Uses
print(Numbers3D) #Printing Numbers 2D

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [110 120 130]]]


In [25]:
print(Numbers3D.ndim) #Shows Dimension Of array

3


In [30]:
arr = np.array([10, 20, 30])

print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)

[10 20 30]
int64
<class 'numpy.ndarray'>
1
