<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/01_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy is designed for numerical operations on entire arrays.**<br>
*So every operation are done on arrays only*

In [34]:
import numpy as np #Importing Library

In [35]:
numbers=np.array([10,20,30,40,50])  #Defining Arrays List 1D
print(numbers) #Printing Numbers

[10 20 30 40 50]


In [36]:
Numbers2D=np.array([[10,20,30],[40,50,60]]) #2D Array List Brackets Uses
print(Numbers2D) #Printing Numbers 2D

[[10 20 30]
 [40 50 60]]


In [37]:
Numbers3D=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[110,120,130]]]) #3D Array List Brackets Uses
print(Numbers3D) #Printing Numbers 2D

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [110 120 130]]]


In [38]:
print(Numbers3D.ndim) #Shows Dimension Of array

3


In [39]:
arr = np.array([10, 20, 30])

print(arr)
print(arr.dtype)
print(type(arr))
print(arr.ndim)

[10 20 30]
int64
<class 'numpy.ndarray'>
1


In [40]:
arr1=np.array([[10,20,30],[40,50,60]])
print(arr1.shape) # shows rows and columns

(2, 3)


In [41]:
print(arr)
print(arr[0])
print(arr[-2])

[10 20 30]
10
20


In [42]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr.ndim)
print(arr[1][2]) # specific number
print(arr[0]) # entire row
print(arr[:,1]) # entire column
print(arr[-1, -1])

2
60
[10 20 30]
[20 50 80]
90


In [43]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[0:2])# slicing for rows
print(arr[:,0:2])# slicing for columns
print(arr[0:2,1:2]) # both slicing

[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]
 [70 80]]
[[20]
 [50]]


In [44]:
arr = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
])

print(arr[1, 1, 0])  # works like 1st array 1st row 0th number
print(arr[0, :, :])  # works like 0th array all rows and columns
print(arr[:, 1, :]) #everything 1st array every column
print(arr[:, :, 0:2]) #each and evry thing but only 0 to 2 n-1 column
#its like [which part of aray,which row, which column]

100
[[10 20 30]
 [40 50 60]]
[[ 40  50  60]
 [100 110 120]]
[[[ 10  20]
  [ 40  50]]

 [[ 70  80]
  [100 110]]]
