<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/01_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy is designed for numerical operations on entire arrays.**<br>
*So every operation are done on arrays only*

In [34]:
import numpy as np #Importing Library

In [35]:
numbers=np.array([10,20,30,40,50])  #Defining Arrays List 1D
print(numbers) #Printing Numbers

[10 20 30 40 50]


In [36]:
Numbers2D=np.array([[10,20,30],[40,50,60]]) #2D Array List Brackets Uses
print(Numbers2D) #Printing Numbers 2D

[[10 20 30]
 [40 50 60]]


In [37]:
Numbers3D=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[110,120,130]]]) #3D Array List Brackets Uses
print(Numbers3D) #Printing Numbers 2D

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [110 120 130]]]
