<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/05_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::2])
print(arr[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


In [3]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(arr[0:2])
print(arr[0:2, 1:3])
print(arr[:, 1:3])

[[10 20 30 40]
 [50 60 70 80]]
[[20 30]
 [60 70]]
[[ 20  30]
 [ 60  70]
 [100 110]]


In [4]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr[:, 0, :])
print(arr[:, :, 1])
print(arr[:, :, 1:3])

[[1 2 3]
 [7 8 9]]
[[ 2  5]
 [ 8 11]]
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
