<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/06_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [16]:
arr = np.array([10, 20, 30])
print(arr + 5)

[15 25 35]


In [17]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)

[11 22 33]


In [18]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
b = np.array([1, 2, 3])
print(a + b)

[[11 22 33]
 [41 52 63]]


In [19]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([
    [1],
    [2]
])
print(a + b)

[[11 21 31]
 [42 52 62]]


In [20]:
a = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
])
b = np.array([1, 2, 3])
print(a.shape)
print(b.shape)

print(a + b)

(2, 2, 3)
(3,)
[[[ 11  22  33]
  [ 41  52  63]]

 [[ 71  82  93]
  [101 112 123]]]
