<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/07_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

In [10]:
arr = np.array([10, 20, 30, 40])
result = (arr * 2)
print(result)

[20 40 60 80]


In [11]:
arr = np.array([10, 20, 30, 40])
print(arr + 5)

[15 25 35 45]


In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr * 2)

[[ 20  40  60]
 [ 80 100 120]]


In [13]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr+2)

[[[3 4 5]
  [6 7 8]]

 [[3 4 5]
  [6 7 8]]]
