<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/08_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

In [31]:
arr = np.array([10, 20, 30, 40])
print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 2)

[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[ 5. 10. 15. 20.]


In [32]:
arr = np.array([10, 20, 30, 40])
print(np.sum(arr))

100


In [33]:
arr = np.array([10, 20, 30, 40])
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))

10
40
25.0
11.180339887498949


In [34]:
arr = np.array([-10, -20, 30, -40])
print(np.abs(arr))

[10 20 30 40]


In [35]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]


In [36]:
arr = np.array([1.234, 2.567, 3.891])
print(np.round(arr))

[1. 3. 4.]


In [37]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

210
[50 70 90]
[ 60 150]
