<a href="https://colab.research.google.com/github/Jeel88/Jeel-sNumpy/blob/main/10_random_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(2,3))

0.4645336451112444
[0.80961475 0.31645874 0.73682836 0.99039033 0.45172171]
[[0.04601459 0.92275684 0.22649467]
 [0.85424163 0.19811218 0.29900063]]


In [10]:
print(np.random.randint(1, 10))
print(np.random.randint(1, 10,5))


4
[2 6 3 9 7]


In [11]:
print(np.random.randint(1, 10, (2, 3)))

[[8 8 8]
 [1 1 3]]


In [14]:
arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr))
print(np.random.choice(arr, 3))

10
[50 20 50]
